package examples

import "github.com/luizbranco/ofx"

var Desjardins = &ofx.OFX{
	SignOn: ofx.SignOn{
		SignOnResponse: ofx.SignOnResponse{
			Status: ofx.Status{
				Code:     0,
				Severity: ofx.Info,
				Message:  "OK",
			},
			DateTimeServer: ofx.DateTime("20080212"),
			Language:       ofx.Language("ENG"),
		},
	},
	Banking: ofx.Banking{
		BankingResponse: []ofx.BankingResponse{
			{
				TransactionUID: ofx.TransactionUID("DESJ-2008021216022711068"),
				Status: ofx.Status{
					Code:     0,
					Severity: ofx.Info,
					Message:  "OK",
				},
				BankStatementResponse: ofx.BankStatementResponse{
					CurrencyDefault: ofx.CurrencySymbol("CAD"),
					BankingAccount: ofx.BankingAccount{
						BankID:      "700000100",
						BranchID:    "0389347",
						ID:          "815-30219-12345-EOP",
						AccountType: ofx.Checking,
					},
					BankTransactionsList: ofx.BankTransactionsList{
						DateStart: ofx.Date("20080113000000"),
						DateEnd:   ofx.Date("20080212000000"),
						Transactions: []ofx.Transaction{
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080114"),
								Amount:          -100,
								FITID:           "Th3DJACES",
								CheckNumber:     "7",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080118"),
								Amount:          -200,
								FITID:           "XwT2KAOtO",
								Name:            "Retrait au GA/CP CREMAZIE DE MTL",
								Memo:            "RGA",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080122"),
								Amount:          -100.14,
								FITID:           "XN5ONAQET",
								Name:            "Paiement facture - AccèsD Intern",
								Memo:            "PWW",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080122"),
								Amount:          -1090.18,
								FITID:           "6Z5ONAQSd",
								Name:            "Paiement facture - AccèsD Intern",
								Memo:            "PWW",
							},
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080122"),
								Amount:          -93.24,
								FITID:           "TsC1NACD6",
								CheckNumber:     "9",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080122"),
								Amount:          -600,
								FITID:           "UsC1NACD6",
								CheckNumber:     "8",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080123"),
								Amount:          1000,
								FITID:           "CtC1NAPjr",
								Name:            "Placement/ING",
								Memo:            "DI",
							},
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080128"),
								Amount:          700,
								FITID:           "gnxzQAPk2",
								Name:            "Placement/ING",
								Memo:            "DI",
							},
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080128"),
								Amount:          -170,
								FITID:           "UH7ZRAEYE",
								CheckNumber:     "10",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080131"),
								Amount:          0.13,
								FITID:           "PBOmSAWsd",
								Name:            "Intérêt sur EOP/",
								Memo:            "INT",
							},
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080201"),
								Amount:          2613.03,
								FITID:           ":WXMTAMse",
								Name:            "Dépôt au comptoir/",
								Memo:            "DSL",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080201"),
								Amount:          -200,
								FITID:           "VRXMTAMun",
								Name:            "Retrait au GA/C.D.S. STE-CECILE",
								Memo:            "RGA",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080201"),
								Amount:          -173.65,
								FITID:           "YrgyTATGw",
								Name:            "Virement-remboursement/à PR 01",
								Memo:            "VAP",
							},
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080204"),
								Amount:          -100,
								FITID:           "M38kVACFZ",
								CheckNumber:     "11",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Check,
								DatePosted:      ofx.DateTime("20080205"),
								Amount:          -1450,
								FITID:           "pYGLWAEO3",
								CheckNumber:     "2",
								Name:            "Chèque/",
								Memo:            "DCN",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080208"),
								Amount:          -47.41,
								FITID:           "vKZXXAQEM",
								Name:            "Achat/STATION CENTRALE D'AUT",
								Memo:            "ACH",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080211"),
								Amount:          -18.97,
								FITID:           "tV1JZASI1",
								Name:            "Assurance/MELOCHE MONNEX/SECURIT",
								Memo:            "RA",
							},
						},
					},
					LedgerBalance: ofx.Balance{
						Amount:        3925.84,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
					AvailableBalance: ofx.Balance{
						Amount:        3925.84,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
				},
			},
			{
				TransactionUID: ofx.TransactionUID("DESJ-2008021216022711068"),
				Status: ofx.Status{
					Code:     0,
					Severity: ofx.Info,
					Message:  "OK",
				},
				BankStatementResponse: ofx.BankStatementResponse{
					CurrencyDefault: ofx.CurrencySymbol("CAD"),
					BankingAccount: ofx.BankingAccount{
						BankID:      "700000100",
						BranchID:    "0389347",
						ID:          "815-30219-54321-ES1",
						AccountType: ofx.Savings,
					},
					BankTransactionsList: ofx.BankTransactionsList{
						DateStart: ofx.Date("20080113000000"),
						DateEnd:   ofx.Date("20080212000000"),
					},
					LedgerBalance: ofx.Balance{
						Amount:        0,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
					AvailableBalance: ofx.Balance{
						Amount:        0,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
				},
			},
			{
				TransactionUID: ofx.TransactionUID("DESJ-2008021216022711068"),
				Status: ofx.Status{
					Code:     0,
					Severity: ofx.Info,
					Message:  "OK",
				},
				BankStatementResponse: ofx.BankStatementResponse{
					CurrencyDefault: ofx.CurrencySymbol("USD"),
					BankingAccount: ofx.BankingAccount{
						BankID:      "1234",
						BranchID:    "5678",
						ID:          "815-30219-11111-EOP",
						AccountType: ofx.Checking,
					},
					BankTransactionsList: ofx.BankTransactionsList{
						DateStart: ofx.Date("20080113000000"),
						DateEnd:   ofx.Date("20080212000000"),
						Transactions: []ofx.Transaction{
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080131"),
								Amount:          0.02,
								FITID:           "e7NmSAWtn",
								Name:            "Intérêt sur EOP/",
								Memo:            "INT",
							},
							{
								TransactionType: ofx.Credit,
								DatePosted:      ofx.DateTime("20080201"),
								Amount:          5029.50,
								FITID:           "qWXMTAMiq",
								Name:            "Dépôt au comptoir/",
								Memo:            "DSL",
							},
							{
								TransactionType: ofx.Debit,
								DatePosted:      ofx.DateTime("20080201"),
								Amount:          -2665,
								FITID:           "uWXMTAMqA",
								Name:            "Retrait au comptoir/",
								Memo:            "RSL",
							},
						},
					},
					LedgerBalance: ofx.Balance{
						Amount:        3046.90,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
					AvailableBalance: ofx.Balance{
						Amount:        3046.90,
						EffectiveDate: ofx.DateTime("20080212160227"),
					},
				},
			},
		},
	},
}
